title: "23ai Select AI with RAG Demo App Deployment"
description: "Oracle 23ai Select AI with RAG 데 애플리케이션 배포"
schemaVersion: 1.0.0
version: "20240724"
locale: "en"
variableGroups:
  - title: "Hidden"
    visible: false
    variables:
      - current_user_ocid
      - tenancy_ocid
      - region
  - title: "Basic Configuration"
    variables:
      - compartment_ocid
      - availability_domain
  - title: "ADB Configuration"
    variables:
      - compute_count
  - title: "Compute Configuration"
    variables:
      - instance_shape
variables:
  current_user_ocid:
    title: User
    type: ocid
    required: true
  tenancy_ocid:
    title: Tenancy
    type: oci:identity:compartment:id
    required: true
  compartment_ocid:
    title: Compartment
    description: The default compartment for created resources.
    type: oci:identity:compartment:id
    required: true
  region:
    required: true
    title: Region
    type: oci:identity:region:name
  availability_domain:
    title: Availability domain
    type: oci:identity:availabilitydomain:name
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
  compute_count:
    title: ADB Compute count (ECPU)
    description: ADB Compute Count
    type: integer
    default: 2
    required: true
  instance_shape:
    title: "Compute Shape"
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    default: VM.Standard.E4.Flex
